version: "3"

networks:
  miniPress.net:
    driver: bridge

services:
  sql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE=${DB_USER_NAME}
    ports:
      - "60609:3306"
    networks:
      miniPress.net:
        aliases:
          - sql.miniPress

  php:
    image: canals/php:latest
    ports:
      - "60608:80"
    volumes:
      - ./admin/public:/var/www/html
      - ./img:/var/www/html/img
      - ./admin/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - miniPress.net
    depends_on:
      - sql
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128

  api :
    image: canals/php:latest
    ports:
      - "60607:80"
    volumes:
      - ./api/public:/var/www/html
      - ./api/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - miniPress.net
    depends_on:
      - sql
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128

  adminer:
    image: adminer
    ports:
      - "60606:8080"
    networks:
      - miniPress.net

  httpd:
    image: httpd
    ports:
      - "60605:80"
    volumes:
      - ./frontend/lib:/usr/local/apache2/htdocs/
      - ./assets:/usr/local/apache2/htdocs/assets
    networks:
      - miniPress.net