version: "3"

networks:
  miniPress.net:
    driver: bridge

services:
  sql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_DATABASE=${DB_USER_NAME}
    ports:
      - "3306:3306"
    networks:
      miniPress.net:
        aliases:
          - sql.miniPress

  php:
    image: canals/php:latest
    ports:
      - "8080:80"
    volumes:
      - ./admin/public:/var/www/html
      - ./img:/var/www/html/img
      - ./admin/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - miniPress.net
    depends_on:
      - sql


  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - miniPress.net

  httpd:
    image: httpd
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    networks:
      - miniPress.net
